### ISSUE TITLE
Make calamine dependency optional

### ISSUE THREAD

**Issue by robinkrahl** [stadelmanma/fitparse-rs#15]
Most users will probably use this crate with the packaged profile without setting `FIT_PROFILE` during the build, making the build script a no-op.  But `fitparser` still pulls in the `calamine` dependency.

What do you think about moving the profile generation behind a feature flag and making the `calamine` dependency optional?  This would reduce the dependencies for users of the default profile, and users who want to regenerate the profile would only have to enable that feature.

**Comment by stadelmanma** [comment]
It’s only a build time dependency, so I didn’t think it would end up getting pulled for people just installing it from crates as an “end user”?

I was actually looking at this yesterday again, I think i know what PR on calamine broke parsing the FIT profile but never was able to figure out why that broke things.

**Comment by robinkrahl** [comment]
Yes, the `build.rs` script is executed locally for all crate users, so the build dependencies are always pulled in.  You might be thinking of the dev dependencies – these are not pulled in by default.

**Comment by stadelmanma** [comment]
That's good to know, I thought it was only present when "building" the binaries uploaded to crates. I'll see if I can do some retooling.

**Comment by stadelmanma** [comment]
@robinkrahl  found an interesting side-effect of making it a "bin script" instead of a build script. If the profile generation fails you can get into a spot where you aren't able to run the update-script again easily. Since it needs the profile module present for compilation.

**Comment by robinkrahl** [comment]
Ah, good point.  This could also be fixed by moving the update script into a separate, unpublished crate.

**Comment by robinkrahl** [comment]
Alternatively, you could write into `OUT_DIR` first and only copy the files over to `src` if everything succeeded.

**Comment by stadelmanma** [comment]
Yeah, this is pushing me towards splitting out the profile as a separate crate, maybe that gets published, maybe it just lives as a “vendored” thing inside this package.
