### ISSUE TITLE
Investigate if the codegen crate would make the profile generation code cleaner

### ISSUE THREAD

**Issue by stadelmanma** [stadelmanma/fitparse-rs#25]
The rust codegen crate looks moderately promising, https://docs.rs/codegen/latest/codegen/ but it might not be worth the effort or make things very verbose which would still hinder readability. Option 2 would be to just define some of my own codegen helper functions to DRY up some of the stuff.

**Comment by robinkrahl** [comment]
An alternative would be to use the `quote!` macro from the `quote` crate that is also used in proc macros.  It makes it possible to write the generated code with syntax highlighting, proper indentation, etc.  See https://github.com/stadelmanma/fitparse-rs/pull/14 for an example using it.

**Comment by stadelmanma** [comment]
Codegen looks to be rather stale as well. I have very limited experience with quote. I wrote a very basic derive macro on my other garmin repo but that's been quite a long time ago now.

**Comment by stadelmanma** [comment]
I’ve started experimenting with using quote in the field types generation file. I think once I get the hang of things it’ll be a good addition. The decode file is a lot more complicated so that’ll be a real test.
