### ISSUE TITLE
Optional CRC validation

### ISSUE THREAD

**Issue by danielalvsaaker** [stadelmanma/fitparse-rs#3]
Upgrading to v0.4 results in failures when validating CRC during parsing of a set of files. These are files which are retrieved from a Garmin Connect export, which I assume results in loss of data, impacting validation. 

A separate function or an enum/bool for opting out in edge cases like this would be nice.

**Comment by danielalvsaaker** [comment]
I can work on this for a pull request if you want. Tell me if there's a specific way you'd prefer to handle this.

**Comment by stadelmanma** [comment]
@danielalvsaaker does the linked PR fix the issue you were having? It doesn’t seem like the expected solution to me.

**Comment by danielalvsaaker** [comment]
It solves the issue, but it doesn't seem optimal to me.

**Comment by danielalvsaaker** [comment]
I was thinking the same.
