### ISSUE TITLE
Dependency security vulnerability

### ISSUE THREAD

**Issue by evensolberg** [stadelmanma/fitparse-rs#8]
There is a security vulnerability in the [calamine](https://crates.io/crates/calamine) crate used in this crate: https://rustsec.org/advisories/RUSTSEC-2021-0015
Updating to version 0.17.0 or newer (0.18.0 is the newest) takes care of it.

I recommend running [cargo audit](https://github.com/RustSec/rustsec/tree/main/cargo-audit), [cargo update](https://doc.rust-lang.org/cargo/commands/cargo-update.html) and [cargo upgrade](https://crates.io/crates/cargo-edit#cargo-upgrade) every now and then to catch issues like this.

**Comment by stadelmanma** [comment]
Hi @evensolberg unfortunately version 0.17.X of Calamine did not parse the excel document correctly (see https://github.com/tafia/calamine/issues/215). I haven’t tried 0.18 but I suspect that the issue remains.

Fortunately it’s just a dev dependency that is only needed when updating the bundled FIT profile.

**Comment by evensolberg** [comment]
Ah. I cloned and tried to compile with 0.18 and it worked fine. I have to admit I didn't try to parse the Excel document. Thanks for the swift reply!

**Comment by evensolberg** [comment]
You're on top of this, so I'll close it.
